export const jobDetails = {
    id: 1,
    title: "Senior Product Designer",
    company: "Acme Technologies",
    status: "Open",
    location: "Bengaluru, India",
    category: "Product",
    availability: "Full-time / Part-time",
    workApproach: "Onsite",
    experience: "4-8 years",
    salary: "₹18L – ₹28L",
    daysOpen: 32,
    targetHire: 2,
};

export const pipelineStages = [
    { id: "all", label: "All", count: 87 },
    { id: "sourcing", label: "Sourcing", count: 39 },
    { id: "screening", label: "Screening", count: 24 },
    { id: "interview", label: "Interview", count: 14 },
    { id: "shortlisted", label: "Shortlisted", count: 9 },
    { id: "offer", label: "Offer", count: 1 },
    { id: "hired", label: "Hired", count: 1 },
    { id: "rejected", label: "Rejected", count: 12 },
];

export const candidatesData = [
    {
        id: "c1",
        name: "Priya Patel",
        initials: "PP",
        role: "UX Lead @ Flipkart",
        experience: "5 yrs",
        aiMatch: 91,
        stage: "Interview",
        subStage: "Round 2",
        lastActivity: "Today, 9am",
        lastActivityAlert: false,
        attentionText: "No tag",
        attentionType: "none", // none, warning, active
        action: "Move",
    },
    {
        id: "c2",
        name: "Rahul Kumar",
        initials: "RK",
        role: "Sr. Designer @ Swiggy",
        experience: "7 yrs",
        aiMatch: 86,
        stage: "Interview",
        subStage: "Round 2",
        lastActivity: "7 days ago",
        lastActivityAlert: true,
        attentionText: "Overdue",
        attentionType: "warning",
        action: "Follow up",
    },
    {
        id: "c3",
        name: "Ananya Nair",
        initials: "AN",
        role: "Product Designer @ Zomato",
        experience: "4 yrs",
        aiMatch: 80,
        stage: "Interview",
        subStage: "Round 1",
        lastActivity: "8 days ago",
        lastActivityAlert: true,
        attentionText: "Overdue",
        attentionType: "warning",
        action: "Follow up",
    },
    {
        id: "c4",
        name: "Suresh Menon",
        initials: "SM",
        role: "Design Lead @ CRED",
        experience: "6 yrs",
        aiMatch: 78,
        stage: "Interview",
        subStage: "Round 3",
        lastActivity: "Yesterday",
        lastActivityAlert: false,
        attentionText: "Awaiting client",
        attentionType: "alert",
        action: "Shortlist",
    },
    {
        id: "c5",
        name: "Kavya Sharma",
        initials: "KS",
        role: "UX Designer @ Ola",
        experience: "3 yrs",
        aiMatch: 74,
        stage: "Interview",
        subStage: "Round 1",
        lastActivity: "2 days ago",
        lastActivityAlert: false,
        attentionText: "AI follow-up queued",
        attentionType: "active",
        action: "Move",
    },
    {
        id: "c6",
        name: "Vikram Rao",
        initials: "VR",
        role: "Principal Designer @ Paytm",
        experience: "8 yrs",
        aiMatch: 71,
        stage: "Interview",
        subStage: "Round 2",
        lastActivity: "3 days ago",
        lastActivityAlert: false,
        attentionText: "No tag",
        attentionType: "none",
        action: "Move",
    },
];

export const followUpNeeded = [
    {
        candidate: "Rahul Kumar",
        initials: "RK",
        description: "No response after Round 2 interview — 7 days",
        tag: "Overdue - 7 days",
        tagColor: "red",
    },
    {
        candidate: "Ananya Nair",
        initials: "AN",
        description: "Client feedback pending for Round 1",
        tag: "Overdue - 8 days",
        tagColor: "red",
    },
    {
        candidate: "Kavya Sharma",
        initials: "KS",
        description: "AI scheduled follow-up for tomorrow 10am",
        tag: "AI Queued",
        tagColor: "blue",
    },
    {
        candidate: "Meera Gupta",
        initials: "MG",
        description: "Offer sent — awaiting response, expires in 1 day",
        tag: "Expires Soon",
        tagColor: "yellow",
    },
];
